import { Database, Server, Globe, Activity, Shield, Terminal, Cpu, Blocks, Layout, Rocket, Cloud, Compass, Users, Box, Zap, Sparkles, CreditCard, Building2, BookOpen, Code, Lightbulb, Search, LogOut, Settings, User, ChevronDown, ChevronRight, Menu, X, Laptop } from 'lucide-react';

export const IconMap: Record<string, any> = {
  'lu:Database': Database,
  'lu:Server': Server,
  'lu:Globe': Globe,
  'lu:Activity': Activity,
  'lu:Shield': Shield,
  'lu:Terminal': Terminal,
  'lu:Cpu': Cpu,
  'lu:Blocks': Blocks,
  'lu:Layout': Layout,
  'lu:Rocket': Rocket,
  'lu:Cloud': Cloud,
  'lu:Compass': Compass,
  'lu:Users': Users,
  'lu:Box': Box,
  'lu:Zap': Zap,
  'lu:Sparkles': Sparkles,
  'lu:CreditCard': CreditCard,
  'lu:Building2': Building2,
  'lu:BookOpen': BookOpen,
  'lu:Code': Code,
  'lu:Lightbulb': Lightbulb,
  'lu:Search': Search,
  'lu:LogOut': LogOut,
  'lu:Settings': Settings,
  'lu:User': User,
  'lu:ChevronDown': ChevronDown,
  'lu:ChevronRight': ChevronRight,
  'lu:Menu': Menu,
  'lu:X': X,
  'lu:Laptop': Laptop,
};
