export interface EmailTheme {
  backgroundColor: string;
  containerColor: string;
  textColor: string;
  primaryColor: string;
}

export interface EmailBlock {
  id: string;
  type: 'heading' | 'paragraph' | 'button' | 'image' | 'divider' | 'spacer';
  content: string; // text, html, or url
  url?: string; // for button/image
  align?: 'left' | 'center' | 'right';
}

export interface EmailDesign {
  theme: EmailTheme;
  blocks: EmailBlock[];
}

export const DEFAULT_EMAIL_THEME: EmailTheme = {
  backgroundColor: '#f4f4f5',
  containerColor: '#ffffff',
  textColor: '#09090b',
  primaryColor: '#000000',
};

export function compileEmailHtml(design: EmailDesign): string {
  const { theme, blocks } = design;

  const blocksHtml = blocks.map(block => {
    const align = block.align || 'left';
    
    switch (block.type) {
      case 'heading':
        return `
          <tr>
            <td align="${align}" style="padding: 16px 32px; font-family: sans-serif;">
              <h2 style="margin: 0; color: ${theme.textColor}; font-size: 24px; font-weight: 600;">
                ${block.content}
              </h2>
            </td>
          </tr>
        `;
      case 'paragraph':
        return `
          <tr>
            <td align="${align}" style="padding: 8px 32px; font-family: sans-serif; font-size: 16px; line-height: 1.5; color: ${theme.textColor};">
              ${block.content}
            </td>
          </tr>
        `;
      case 'button':
        return `
          <tr>
            <td align="${align}" style="padding: 24px 32px;">
              <a href="${block.url || '#'}" style="display: inline-block; padding: 12px 24px; background-color: ${theme.primaryColor}; color: #ffffff; text-decoration: none; border-radius: 6px; font-family: sans-serif; font-weight: 500; font-size: 16px;">
                ${block.content}
              </a>
            </td>
          </tr>
        `;
      case 'image':
        return `
          <tr>
            <td align="${align}" style="padding: 16px 32px;">
              <img src="${block.content}" alt="" style="max-width: 100%; height: auto; display: block; border-radius: 4px;" />
            </td>
          </tr>
        `;
      case 'divider':
        return `
          <tr>
            <td style="padding: 24px 32px;">
              <div style="height: 1px; background-color: #e4e4e7; width: 100%;"></div>
            </td>
          </tr>
        `;
      case 'spacer':
        return `
          <tr>
            <td style="height: ${parseInt(block.content) || 32}px; line-height: ${parseInt(block.content) || 32}px; font-size: ${parseInt(block.content) || 32}px;">
              &nbsp;
            </td>
          </tr>
        `;
      default:
        return '';
    }
  }).join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Email</title>
    </head>
    <body style="margin: 0; padding: 40px 0; background-color: ${theme.backgroundColor};">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: ${theme.backgroundColor};">
        <tr>
          <td align="center">
            <table width="600" border="0" cellspacing="0" cellpadding="0" style="background-color: ${theme.containerColor}; border-radius: 8px; overflow: hidden; margin: 0 auto; border: 1px solid #e4e4e7;">
              ${blocksHtml}
            </table>
            <div style="padding: 24px; font-family: sans-serif; font-size: 12px; color: #71717a; text-align: center;">
              This email was generated by {{company.name}}.<br/>
              {{company.address}}
            </div>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `.trim();
}
